// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "rescript/lib/es6/caml_array.js";

function readFileAsText(params) {
  var reader = new FileReader();
  var file;
  if (params.e.target.files.length > 0) {
    file = Caml_array.get(params.e.target.files, 0);
  } else {
    var items = params.e.dataTransfer.items;
    var files = params.e.dataTransfer.files;
    file = items.length > 0 && Caml_array.get(items, 0).kind === "file" ? Caml_array.get(items, 0).getAsFile() : Caml_array.get(files, 0);
  }
  reader.addEventListener("load", (function (_e) {
          params.onLoad({
                result: reader.result,
                file: file
              });
        }), {
        once: true
      });
  reader.readAsText(file);
}

export {
  readFileAsText ,
}
/* No side effect */
