// Generated by ReScript, PLEASE EDIT WITH CARE


var $$File = {};

var $$FileReader = {};

var $$DataTransferItem = {};

var $$DataTransfer = {};

export {
  $$File ,
  $$FileReader ,
  $$DataTransferItem ,
  $$DataTransfer ,
}
/* No side effect */
